-- MySQL Script generated by MySQL Workbench
-- Wed Mar  6 15:03:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`tb_assunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_assunto` (
  `id_assunto` INT NOT NULL AUTO_INCREMENT,
  `assunto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_assunto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_livro` (
  `id_livro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(150) NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `autores` VARCHAR(150) NOT NULL,
  `edicao` VARCHAR(45) NOT NULL,
  `editora` VARCHAR(100) NOT NULL,
  `ano` INT NOT NULL,
  `assunto` INT NOT NULL,
  `upload` VARCHAR(100) NULL,
  PRIMARY KEY (`id_livro`),
  INDEX `fk_Assunto_livro_idx` (`assunto` ASC),
  CONSTRAINT `fk_Assunto_livro`
    FOREIGN KEY (`assunto`)
    REFERENCES `biblioteca`.`tb_assunto` (`id_assunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_exemplar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_exemplar` (
  `id_exemplar` INT NOT NULL AUTO_INCREMENT,
  `livro` INT NOT NULL,
  `circular` TINYINT NOT NULL,
  `numero` INT NULL,
  PRIMARY KEY (`id_exemplar`),
  INDEX `fk_Livro_idx` (`livro` ASC),
  CONSTRAINT `fk_Livro`
    FOREIGN KEY (`livro`)
    REFERENCES `biblioteca`.`tb_livro` (`id_livro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `assunto` INT NOT NULL,
  PRIMARY KEY (`id_categoria`),
  INDEX `fk_Assunto_categoria_idx` (`assunto` ASC),
  CONSTRAINT `fk_Assunto_categoria`
    FOREIGN KEY (`assunto`)
    REFERENCES `biblioteca`.`tb_assunto` (`id_assunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `grupo` INT NOT NULL,
  `email` VARCHAR(100) NULL,
  `senha` VARCHAR(45) NULL,
  `funcao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
