-- MySQL Script generated by MySQL Workbench
-- Sat May 18 18:27:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`tb_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_autores` (
  `id_autor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_autor` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_categorias` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(255) NOT NULL,
  `assunto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_editoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_editoras` (
  `id_editora` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_editora` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_editora`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_livros` (
  `id_livro` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `edicao` VARCHAR(45) NULL DEFAULT NULL,
  `ano` YEAR(4) NOT NULL,
  `imagem` VARCHAR(100) NULL DEFAULT NULL,
  `categoria` INT(11) NOT NULL,
  `editora` INT(11) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_livro`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC),
  INDEX `fk_tb_livro_tb_categoria1_idx` (`categoria` ASC),
  INDEX `fk_tb_livro_tb_editora1_idx` (`editora` ASC),
  CONSTRAINT `fk_livros_categorias`
    FOREIGN KEY (`categoria`)
    REFERENCES `biblioteca`.`tb_categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livros_editoras`
    FOREIGN KEY (`editora`)
    REFERENCES `biblioteca`.`tb_editoras` (`id_editora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_exemplares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_exemplares` (
  `id_exemplar` VARCHAR(100) NOT NULL,
  `livro` INT(11) NOT NULL,
  `tipo_exemplar` INT(11) NOT NULL,
  PRIMARY KEY (`id_exemplar`),
  INDEX `fk_tb_exemplar_tb_livro1_idx` (`livro` ASC),
  CONSTRAINT `fk_exemplares_livros`
    FOREIGN KEY (`livro`)
    REFERENCES `biblioteca`.`tb_livros` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(255) NOT NULL,
  `grupo` INT(11) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_emprestimos` (
  `exemplar` VARCHAR(100) NOT NULL,
  `usuario` INT(11) NOT NULL,
  `data_emprestimo` DATE NOT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`exemplar`, `usuario`, `data_emprestimo`),
  INDEX `fk_tb_exemplar_has_tb_pessoa_tb_pessoa1_idx` (`usuario` ASC),
  INDEX `fk_tb_exemplar_has_tb_pessoa_tb_exemplar1_idx` (`exemplar` ASC),
  CONSTRAINT `fk_emprestimos_exemplares`
    FOREIGN KEY (`exemplar`)
    REFERENCES `biblioteca`.`tb_exemplares` (`id_exemplar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimos_usuarios`
    FOREIGN KEY (`usuario`)
    REFERENCES `biblioteca`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_livros_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_livros_autores` (
  `id_livro_autor` INT(11) NOT NULL AUTO_INCREMENT,
  `livro` INT(11) NOT NULL,
  `autor` INT(11) NOT NULL,
  PRIMARY KEY (`id_livro_autor`),
  INDEX `fk_livros_autores_autores_idx` (`autor` ASC),
  INDEX `fk_livros_autores_livros_idx` (`livro` ASC),
  CONSTRAINT `fk_livros_autores_autores`
    FOREIGN KEY (`autor`)
    REFERENCES `biblioteca`.`tb_autores` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livros_autores_livros`
    FOREIGN KEY (`livro`)
    REFERENCES `biblioteca`.`tb_livros` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
